### ISSUE TITLE
None of the available audio providers recognised the selected file as containing audio data.

### ISSUE THREAD

**Issue by yitaiwt** [TypesettingTools/Aegisub#248] opened 2024-12-30 06:20 UTC
Unable to open audio file（MP3）。
![image](https://github.com/user-attachments/assets/42d5a222-0e22-417d-9cff-8aff7c7e5e22)

**Comment by yitaiwt** [comment] 2024-12-30 06:21
3.4

**Comment by CoffeeFlux** [comment] 2024-12-30 07:03
Probably a duplicate of https://github.com/TypesettingTools/Aegisub/issues/219

**Comment by CoffeeFlux** [comment] 2024-12-30 20:22
Fixed by https://github.com/TypesettingTools/Aegisub/pull/231

**Comment by arch1t3cht** [comment] 2024-12-30 20:22
Should be fixed now that #219 is fixed.

**Closed** 2024-12-30 20:22 UTC
